Lesson 7
jakubboucek/kirillova-skolka pull request #9
Opened 2019-06-18 13:08 UTC by BadKoldrysh

Modify method for including .html file for strong checking file existing
Change 'assets/nice-html.html' name

2019-06-18 13:11 UTC, BadKoldrysh commented
Tady mám dvě varianty: přes Exceptions nebo přes IF...ELSE. Myslím, že Exception je zbytečný v tomto případě

2019-06-18 13:14 UTC, BadKoldrysh commented
Použil jsem die() proto, aby dokončit běh programu. Ale nejsem jistý, že tento způsob bude dobrý pro pravý web

2019-06-18 15:30 UTC, jakubboucek requested changes
Skvělé!

Předně pozor, **aplikace je v tuto chvíli rozbitá**, protože:
- je commitnutý přejmenovaný soubor `www/assets/nice-html1.html`, ale prosím v repozitáři nechávej aplikaci funkční. Smyslem této lekce je aplikaci vylepšit a ne ji rozbít :)
- funkce `printNiceHtmlHeader()` je také rozbitá, protože už nevypisuje šablonu na výstup (chybí tam `echo`).

## `die()` vs Exception
V tomto případě je použití `die()` nevhodné z několika důvodů:
- kromě výpisu informace na výstup je ukončení scriptu pomocí `die()` v podstatě korektní a neindikuje v procesu chybu. 
- v systémovém logu, ani v logu PHP se proto chyba nijak neeviduje,
- zachová se pouze hláška vložená do argumentu funkce `die(...)`, ale chybý dam další důležité informace o tom, kde k chybě došlo (tzv. [Stacktrace](https://en.wikipedia.org/wiki/Stack_trace)).

Tyhle všechny věci použití `Exception` řeší – PHP totiž ví, že stav aplikace není v pořádku a využívá mnoho dalších prostředků (signály, [Exit status](https://en.wikipedia.org/wiki/Exit_status), logy, [`stderr`](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)), atd.), které teď sice nejsou zřejmé, ale s rostoucí aplikací budou nabírat na důležitosti.

Chápu ale, že tobě použití Exceptions, tak, jak jsi ho nastínil, nedává smysl. To z důvodu, **protože jsi výjimku hned odchytil přes `try...catch`**. Ale když ve funkci `printNiceHtmlHeader()` úplně vypustíš `try` a celý `catch` blok, tak se ta aplikace začne chovat tak, jak mi to dává smysl.

Co se stane při chybě:
- vyhodí se Exception, který zastaví běh funkce a postupně se bude propagovat přes řetězec volání (což je v tomto případě pouze jedna funkce).
- protože výjimku žádný blok `try...catch` nezachytí, tak probublá až nahoru, až k samotnému procesu PHP. 
- PHP tedy ukončí beh scriptu, ale vygeneruje **Fatal error: Uncaught Exception**, který se zaloguje (na testovacím prostředí se místo logu vypíše chyba na obrazovku).

Tedy prostě vyhoď z funkce tu `try...catch` obálku a je to správně.

### Proč je `die()` problematické?
S funkcí `die()` je jeden obrovský problém. Ona totiž **zabije script** a neexistuje způsob, jak tomu zabránit.

Představ si, že se aplikace rozroste a ty by jsi chtěl pomocí funkce `printNiceHtmlHeader()` do stránky dát nějakou nedůležitou ilustraci (například vložit [banner s počasím](http://www.lastminute7.cz/pocasi/bannery.php)). Když by došlo k chybě, tak se stránka v půlce „přetrhne“ a nepůjde ji načíst. A ani tomu nejde v kódu zabránit.

Pokud ale použiješ výjimku, tak volání funkce `printNiceHtmlHeader()` prostě vložíš do `try...catch` a v případě chyby se banner s počasím nevykreslí – aplikace to ale může ošetřit a pokračovat dál.

Výjimka poskytuje robusní a velmi striktní princip zpracování chyb, ale zároveň umožňuje chybu úplně programově ošetřit.

## Několik poznámek
Chybový stav je možné indikovat návratovou hodnotou `> 0` pomocí volání `die()` s číselným argumentem (např. `die(1)`), ale to nemá vliv při použití na webu – uplatní se to jen při volání php scriptů přes `CLI` *([learn more](https://www.php.net/manual/en/features.commandline.introduction.php))*.

Chybu je možné indikovat také voláním funkce [`trigger_error()`](https://www.php.net/manual/en/function.trigger-error.php), které lze chybu předat. Je to velmi podobné výjimce – v malé aplikaci, jako je tato, to má srovnatelné výhody, ve větších aplikacích už to ale vede k velkým problémům:
- chyba se špatně ošetřuje, pokud je aplikace jsou v chybovém stavu, je velmi obtížné chybu správně a korektně ošetřit a aplikaci stabilizovat.
- výjimky poskytují mnohem podrobnější [Stacktrace](https://en.wikipedia.org/wiki/Stack_trace), zatímco klasická chyba způsobuje ztrátu dat a při zachycení chyby mohou informace o příčině chyby už být poškozené.
- Klasické chyby jsou de-facto deprecated a i PHP v nových verzích od nich postupně upouští a převádí interní chyby na výjimky *([learn more](https://www.php.net/manual/en/language.errors.php7.php))*.

2019-06-18 15:30 UTC, jakubboucek commented on www/libs/fce.php
> +        file_get_contents('./assets/nice-html.html');
Tento řádek je chybně, zde musí být `echo`, jinak se sice soubor načte, ale nijak nepoužije.

2019-06-18 15:47 UTC, jakubboucek commented
## „Ať se postará někdo jiný“

Při programování se snažím aplikovat moji oblíbenou poučku: **„ať se postará někdo jiný“** *([zdroj](https://phpfashion.com/co-je-dependency-injection))*.

Co to znamená?

V případě této lekce to znamená, že funkce `printNiceHtmlHeader()` dostala za úkol načíst šablonu ze souboru. Ona udělá, co je její business.

Ale pokud dojde k nějaké chybě (právě proto, že třeba nejde načíst potřebný soubor), tak by už tato funkce neměla řešit nějaké vypisování chyby, logování, a posílání návratových hodnot.
 **To totiž není její business!**

Ona má za úkol vypsat šablonu a buď to udělá a nebo vyhodí výjimku.

**Kdo ale tu výjimku zachytí a zpracuje?**

To funkci `printNiceHtmlHeader()` nezajímá, **ať se postará někdo jiný**. Někdo, kdo tu funkci zavolal.

### Výsledek?
Výsledkem je, že funkce `printNiceHtmlHeader()` je krátká a velmi přehledná.

2019-06-19 07:14 UTC, jakubboucek approved these changes

2019-06-19 07:14 UTC, merged